#!/usr/bin/env php
<?php


use console\commands\ParseCommands;
use Symfony\Component\Console\Application;
require __DIR__."/vendor/autoload.php";




$app = new Application();


$app->add(new ParseCommands());
$app->run();

